In [1]:

import pandas as pd
import math as mt
import numpy as np
import matplotlib.pyplot as plt

### Tarea Examen Teoría del Riesgo

#### Aviña Santiago Gerardo
#### Cabrera Ramírez Eduardo Tadeo
#### San Martín García Luis Uriel

In [38]:
d = {'t': [1,2,3,4,5,6], 'Grupo 1': ['Calculo II', 'Probabilidad I','Estadistica I','Probabilidad II','Estadistica II', 'Procesos Estocasticos']
     ,'Grupo 2': ['Seguro de Vida', 'Seguro de Daños','Matemáticas Financieras II', 'Probabilidad I','Matemáticas Actuariales I','Matemáticas Actuariales II']
     ,'Grupo 3': ['Matemáticas Financieras I', 'Matemáticas Financieras II', 'Finanzas Corporativas','Aplicación a las Matemáticas Financieras',' Probabilidad I','Procesos Estocásticos I']}
df = pd.DataFrame(data=d)
df

t                Grupo 1                     Grupo 2  \
0  1             Calculo II              Seguro de Vida   
1  2         Probabilidad I             Seguro de Daños   
2  3          Estadistica I  Matemáticas Financieras II   
3  4        Probabilidad II              Probabilidad I   
4  5         Estadistica II   Matemáticas Actuariales I   
5  6  Procesos Estocasticos  Matemáticas Actuariales II   

                                    Grupo 3  
0                 Matemáticas Financieras I  
1                Matemáticas Financieras II  
2                     Finanzas Corporativas  
3  Aplicación a las Matemáticas Financieras  
4                            Probabilidad I  
5                   Procesos Estocásticos I

In [5]:
pro=[]
for i in range(1,19):
    aux=0
    for j in range(1,4):
        calif=float(input('Materia '+str(i)+' Calificacion '+str(j)+': ' ))
        aux=aux+calif
    print('\n')
    pro.append(aux/3)
print(pro)

Materia 1 Calificacion 1: 8
Materia 1 Calificacion 2: 7
Materia 1 Calificacion 3: 8


Materia 2 Calificacion 1: 6
Materia 2 Calificacion 2: 6
Materia 2 Calificacion 3: 6


Materia 3 Calificacion 1: 8
Materia 3 Calificacion 2: 6
Materia 3 Calificacion 3: 8


Materia 4 Calificacion 1: 6
Materia 4 Calificacion 2: 7
Materia 4 Calificacion 3: 7


Materia 5 Calificacion 1: 7
Materia 5 Calificacion 2: 5
Materia 5 Calificacion 3: 8


Materia 6 Calificacion 1: 7
Materia 6 Calificacion 2: 7
Materia 6 Calificacion 3: 8


Materia 7 Calificacion 1: 9
Materia 7 Calificacion 2: 6
Materia 7 Calificacion 3: 10


Materia 8 Calificacion 1: 9
Materia 8 Calificacion 2: 9
Materia 8 Calificacion 3: 10


Materia 9 Calificacion 1: 8
Materia 9 Calificacion 2: 8
Materia 9 Calificacion 3: 8


Materia 10 Calificacion 1: 6
Materia 10 Calificacion 2: 6
Materia 10 Calificacion 3: 7


Materia 11 Calificacion 1: 8
Materia 11 Calificacion 2: 9
Materia 11 Calificacion 3: 6


Materia 12 Calificacion 1: 8
Materia 12 Califi

In [6]:
d1 = {'t': [1,2,3,4,5,6], 'Grupo 1': [7.666666666666667, 6.0, 7.333333333333333, 6.666666666666667, 6.666666666666667, 7.333333333333333]
     ,'Grupo 2': [8.333333333333334, 9.333333333333334, 8.0, 6.333333333333333, 7.666666666666667, 7.666666666666667]
     ,'Grupo 3': [10.0, 8.333333333333334, 9.333333333333334, 8.0, 6.666666666666667, 7.333333333333333]}
df1 = pd.DataFrame(data=d1)
df1

t   Grupo 1   Grupo 2    Grupo 3
0  1  7.666667  8.333333  10.000000
1  2  6.000000  9.333333   8.333333
2  3  7.333333  8.000000   9.333333
3  4  6.666667  6.333333   8.000000
4  5  6.666667  7.666667   6.666667
5  6  7.333333  7.666667   7.333333

In [7]:
t=[1,2,3,4,5,6]
k=[1,2,3]

In [11]:
x_jr=np.array([[ 7.666667, 8.333333, 10.000000 ],
[ 6.000000, 9.333333, 8.333333 ],
[ 7.333333, 8.000000, 9.333333 ],
[ 6.666667, 6.333333, 8.000000 ],
[ 6.666667, 7.666667, 6.666667 ],
[ 7.333333, 7.666667, 7.333333 ]])
x_jr

array([[ 7.666667,  8.333333, 10.      ],
       [ 6.      ,  9.333333,  8.333333],
       [ 7.333333,  8.      ,  9.333333],
       [ 6.666667,  6.333333,  8.      ],
       [ 6.666667,  7.666667,  6.666667],
       [ 7.333333,  7.666667,  7.333333]])

### Estimador para la muestra

In [12]:
m_hat=(1/3)*sum(sum(x_jr[r][j]/len(t)for r in range(0,6))for j in range(0,3))
m_hat

7.703703666666666

### Estimador por grupo

In [13]:
Mj=[]
for i in range(0,3):
    aux=0
    for j in range(0,6):
        aux=x_jr[j][i]+aux
    Mj.append(aux/6)
Mj

[6.9444445, 7.888888833333333, 8.277777666666665]

### Varianza de la muestra

In [14]:
S_hat=(1/3)*sum(sum((x_jr[r][j]-Mj[j])**2/5 for r in range(0,6))for j in range(0,3))
S_hat

0.9555554148149109

### Heterogeneidad de la muestra

In [15]:
a_hat_2=((1/2)*sum((Mj[j]-m_hat)**2 for j in range(0,3)))-(1/len(t))*S_hat
a_hat_2

0.31090525699587485

### Factor de Credibilidad

In [17]:
Z=(a_hat_2*6)/(S_hat+a_hat_2*6)
Z

0.6612691127426613

### Estimador de la credibilidad de la muestra con ajuste por grupo

In [18]:
M_hatj=[]
for j in range(0,3):
    M_hatj.append(m_hat*(1-Z)+Mj[j]*Z)
M_hatj

[7.201629031183268, 7.826160897521435, 8.083321071295297]

In [19]:
d2 = { 'Grupo ': ['Grupo 1','Grupo 2','Grupo 3'],
       'Estimador individual ': Mj,
      'Varianza colectiva ': [' ',S_hat,' '],
     'Estimador colectivo m':[' ',m_hat , ' '],
     'a ajustado':[' ',a_hat_2,' '],
     'Factor de credibilidad Z':[' ',Z,' '],
     'Ajuste con credebilidad':M_hatj}
df2 = pd.DataFrame(data=d2)
df2

Grupo   Estimador individual  Varianza colectiva  Estimador colectivo m  \
0  Grupo 1               6.944445                                             
1  Grupo 2               7.888889            0.955555                7.7037   
2  Grupo 3               8.277778                                             

  a ajustado Factor de credibilidad Z  Ajuste con credebilidad  
0                                                     7.201629  
1   0.310905                 0.661269                 7.826161  
2                                                     8.083321

### Bühlmann-Straub

In [20]:
x_jr=np.array([[ 7.666667, 8.333333, 10.000000 ],
[ 6.000000, 9.333333, 8.333333 ],
[ 7.333333, 8.000000, 9.333333 ],
[ 6.666667, 6.333333, 8.000000 ],
[ 6.666667, 7.666667, 6.666667 ],
[ 7.333333, 7.666667, 7.333333 ]])
x_jr

array([[ 7.666667,  8.333333, 10.      ],
       [ 6.      ,  9.333333,  8.333333],
       [ 7.333333,  8.      ,  9.333333],
       [ 6.666667,  6.333333,  8.      ],
       [ 6.666667,  7.666667,  6.666667],
       [ 7.333333,  7.666667,  7.333333]])

### Pesos de las materias

In [21]:
d3= { 'Grupo ': ['Grupo 1','Grupo 2','Grupo 3'], 't=1':[7.666667,  8.333333, 10.],'wjq1':[2,1,1],
      't=2':[6.      ,  9.333333,  8.333333],'wjq2':[3,1,2],
      't=3':[7.333333,  8.      ,  9.333333],'wjq3':[4,2,3],
      't=4':[6.666667,  6.333333,  8.      ],'wjq4':[5,3,4],
      't=5':[6.666667,  7.666667,  6.666667],'wjq5':[5,4,3],
      't=6':[7.333333,  7.666667,  7.333333],'wjq6':[6,5,6]}
df3 = pd.DataFrame(data=d3)
df3

Grupo         t=1  wjq1       t=2  wjq2       t=3  wjq3       t=4  wjq4  \
0  Grupo 1   7.666667     2  6.000000     3  7.333333     4  6.666667     5   
1  Grupo 2   8.333333     1  9.333333     1  8.000000     2  6.333333     3   
2  Grupo 3  10.000000     1  8.333333     2  9.333333     3  8.000000     4   

        t=5  wjq5       t=6  wjq6  
0  6.666667     5  7.333333     6  
1  7.666667     4  7.666667     5  
2  6.666667     3  7.333333     6

In [22]:
w_jq=np.array([[2,1,1],
[3,1,2],
[4,2,3],
[5,3,4],
[5,4,3],
[6,5,6]])
w_jq

array([[2, 1, 1],
       [3, 1, 2],
       [4, 2, 3],
       [5, 3, 4],
       [5, 4, 3],
       [6, 5, 6]])

### Suma de pesos por grupo 

In [24]:
wj=[]
for j in range(0,3):
    aux=0
    for q in range(0,6):
        aux=aux+w_jq[q][j]
    wj.append(aux)
wj

[25, 16, 19]

#### Suma de todos los pesos

In [25]:
W=sum(wj)
W

60

### Promedio ponderado de las calificaciones por grupo con el peso

In [26]:
x_wj=[]
for j in range(0,3):
    aux=0
    for q in range(0,6):
        aux=aux+((w_jq[q][j]/wj[j])*x_jr[q][j])
    x_wj.append(aux)
x_wj

[6.933333360000001, 7.60416675, 7.929824421052631]

### Promedio ponderado de todas las calificaciones

In [27]:
x_ww=sum((x_wj[j]/W)*wj[j] for j in range(0,3))
x_ww

7.427777766666667

#### Varianza 

In [28]:
s_hat_str=(1/3)*sum((1/5)*sum(w_jq[q][j]*((x_jr[q][j]-x_wj[j])**2) for q in range(0,6))for j in range(0,3))
s_hat_str

2.1451506938404923

#### Calculo de C

In [29]:
c=sum((wj[j]/W)*(1-(wj[j]/W)) for j in range(0,3))
c

0.6549999999999999

#### Heterogeneidad

In [30]:
a_hat_str=(W*(sum(wj[j]*(((x_wj[j]-x_ww)**2))for j in range(0,3))-((2)*s_hat_str)))/((W**2)-sum(wj[j]**2 for j in range(0,3)))
a_hat_str

0.18087418803822722

### Credibilidad Bühlman-Straub por grupo

In [31]:
zj=[]
for j in range(0,3):
    zj.append(a_hat_str*wj[j]/(s_hat_str+(a_hat_str*wj[j])))
zj

[0.6782437441081335, 0.5743020293339818, 0.6156856275807208]

#### Factores de riesgo de los grupos

In [32]:
Z=sum(zj)
Z

1.868231401022836

### Estimador de calificación de los grupos

In [33]:
x_zw=sum((zj[j]/Z)*x_wj[j] for j in range(0,3))
x_zw

7.467949254464646

#### Calificación con peso y credibilidad por grupo

In [34]:
M_jalpha=[]
for j in range(0,3):
    M_jalpha.append((1-zj[j])*x_zw+zj[j]*x_wj[j])
M_jalpha

[7.1053493685432265, 7.546179238581392, 7.752319156269319]

In [35]:
d4 = { 'Grupo ': ['Grupo 1','Grupo 2','Grupo 3'],
      'Estimador individual Straub':x_wj,
      'Estimador colectivo ajustado m Straub':[' ',x_zw , ' '],
     'a ajustado Straub':[' ',a_hat_str,' '],
     'Factor de credibilidad Z por grupo Straub':zj,
     'Ajuste con credebilidad ajustada Straub':M_jalpha}
df4 = pd.DataFrame(data=d4)
df4

Grupo   Estimador individual Straub Estimador colectivo ajustado m Straub  \
0  Grupo 1                     6.933333                                         
1  Grupo 2                     7.604167                               7.46795   
2  Grupo 3                     7.929824                                         

  a ajustado Straub  Factor de credibilidad Z por grupo Straub  \
0                                                     0.678244   
1          0.180874                                   0.574302   
2                                                     0.615686   

   Ajuste con credebilidad ajustada Straub  
0                                 7.105349  
1                                 7.546179  
2                                 7.752319

## Calificación esperada 7.46795